erofs: Include missing xarray header file
error: implicit declaration of function 'xa_unlock' [-Werror,-Wimplicit-function-declaration]
        xa_unlock(&sbi->workstn_tree);
        ^